# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d2f337eb78b2a88d6a502b64e38098a3e67290e6c7f782c48833ada9e480213310acfd0439e0020fa5583e8278aaff5ee1459eb5ab73e929374d9d1901a7188

test:
  secret_key_base: 0cdce71eae6f3b73893534e0d8caab51bee95eeba6c6bac07abb6a85a6ae889d95cb02f260d27b4840e3f8aa013661ab661433960d8cdca520bc1e49b99da94f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
